# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Cereal Talk
tagline:          'A blog, best enjoyed with cereal.'
description:      'Bite sized.'
url:              http://cerealtalk.co.uk
baseurl:          /

author:
  name:           'MOCSV'
  url:            

plugins: [jekyll-paginate]

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mocsv/mocsv.github.io
